@startuml
hide circle
skinparam linetype ortho

entity "COMPANY" as COMPANY {
  * company_id : int <<PK>>
  --
  company_name : string
  address : string
  phone : string
  email : string
  status : string
  created_at : datetime
  updated_at : datetime
}

entity "USER" as USER {
  * user_id : int <<PK>>
  --
  company_id : int <<FK>>
  full_name : string
  email : string
  password : string
  status : string
  created_at : datetime
  updated_at : datetime
}

entity "ROLE" as ROLE {
  * role_id : int <<PK>>
  --
  role_name : string
  description : string
  status : string
  created_at : datetime
  updated_at : datetime
}

entity "PERMISSION" as PERMISSION {
  * permission_id : int <<PK>>
  --
  permission_name : string
  module_name : string
  action : string
  created_at : datetime
  updated_at : datetime
}

entity "USER_ROLE" as USER_ROLE {
  * user_role_id : int <<PK>>
  --
  user_id : int <<FK>>
  role_id : int <<FK>>
  assigned_at : datetime
}

entity "ROLE_PERMISSION" as ROLE_PERMISSION {
  * role_permission_id : int <<PK>>
  --
  role_id : int <<FK>>
  permission_id : int <<FK>>
  created_at : datetime
}

entity "PRODUCT" as PRODUCT {
  * product_id : int <<PK>>
  --
  product_name : string
  description : string
  status : string
  created_at : datetime
  updated_at : datetime
}

entity "COMPANY_PRODUCT" as COMPANY_PRODUCT {
  * company_product_id : int <<PK>>
  --
  company_id : int <<FK>>
  product_id : int <<FK>>
  assigned_at : datetime
}

entity "ACTIVATION_TOKEN" as ACTIVATION_TOKEN {
  * token_id : int <<PK>>
  --
  user_id : int <<FK>>
  token : string
  token_type : string
  expired_at : datetime
  status : string
  created_at : datetime
}

COMPANY ||--o{ USER : memiliki
USER ||--o{ USER_ROLE : memiliki
ROLE ||--o{ USER_ROLE : diberikan

ROLE ||--o{ ROLE_PERMISSION : memiliki
PERMISSION ||--o{ ROLE_PERMISSION : digunakan

COMPANY ||--o{ COMPANY_PRODUCT : memiliki_akses
PRODUCT ||--o{ COMPANY_PRODUCT : diberikan

USER ||--o{ ACTIVATION_TOKEN : memiliki

@enduml